[package]
name = "varuna"
version = "0.0.1"
edition = "2024.beta"

[dependencies]

deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "main"}

[addresses]
varuna = "0x0"
